//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HasanBozkusCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Educations
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Bu alaný boþ geçme")]
        [StringLength(100, ErrorMessage = "En fazla 100 karakter giriniz")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Bu alaný boþ geçme")]
        [StringLength(100, ErrorMessage = "En fazla 100 karakter giriniz")]
        public string SubTitle { get; set; }

        [Required(ErrorMessage = "Bu alaný boþ geçme")]
        [StringLength(100, ErrorMessage = "En fazla 100 karakter giriniz")]
        public string SubTitle2 { get; set; }

       
        [StringLength(10, ErrorMessage = "En fazla 10 karakter giriniz")]
        [Required(ErrorMessage = "Bu alaný boþ geçme")]
        public string GNO { get; set; }

        [Required(ErrorMessage = "Bu alaný boþ geçme")]
        [StringLength(100, ErrorMessage = "En fazla 100 karakter giriniz")]
        public string DateTime { get; set; }
    }
}
